services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./todo-frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./todo-backend
    environment:
      MONGO_URL: mongodb://mongo:27017/tododb
      REDIS_URL: redis://redis:6379

  mongo:
    image: mongo:8
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7

volumes:
  mongo-data: