services:
  app:
    image: todo-backend
    build: .
    ports:
      - "3123:3000"
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database?authSource=admin
  
  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "3456:27017"

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6378:6379"