services:
  server:
    image: todo-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports: 
      - "3123:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  redis:
    image: redis:7
    ports:
      - "6378:6379"

  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    ports:
      - "3456:27017"